Feat/is3 9 new insurance type icon
coverwallet/styleguide pull request #94
Opened 2022-01-13 17:51 UTC by nemanja-jevtovic

Added new insurance type icon needed for Uber France.

2022-01-13 20:41 UTC, Griffin404 approved these changes

2022-01-14 07:26 UTC, medvyk requested changes
I just want to double-check with you that when using icon moon you put the new icons at the bottom. It seems trivial but we had big problems in the past and we cannot detect them just by looking at the code.

2022-01-14 09:24 UTC, nemanja-jevtovic commented
@medvyk Yes, it took like 5 minutes to move the damn thing all the way down xD

2022-01-14 10:12 UTC, medvyk commented
> @medvyk Yes, it took like 5 minutes to move the damn thing all the way down xD

haha ok. Thanks! :)

2022-01-14 10:44 UTC, merged